name: Deploy to AWS ECS

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY_BACKEND: sentiment-analysis-backend
  ECR_REPOSITORY_FRONTEND: sentiment-analysis-frontend
  ECS_SERVICE_BACKEND: sentiment-analysis-backend-service
  ECS_SERVICE_FRONTEND: sentiment-analysis-frontend-service
  ECS_CLUSTER: sentiment-analysis-cluster
  ECS_TASK_DEFINITION_BACKEND: sentiment-analysis-backend-task
  ECS_TASK_DEFINITION_FRONTEND: sentiment-analysis-frontend-task
  CONTAINER_NAME_BACKEND: sentiment-analysis-backend
  CONTAINER_NAME_FRONTEND: sentiment-analysis-frontend

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push backend image to Amazon ECR
      id: build-backend-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build backend image
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Build, tag, and push frontend image to Amazon ECR
      id: build-frontend-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build frontend image
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$IMAGE_TAG ./frontend
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Fill in the new image ID in the Amazon ECS task definition (backend)
      id: task-def-backend
      run: |
        # Get the working task definition (revision 14) that has proper ephemeral storage
        TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition sentiment-analysis-backend-task:14 --query taskDefinition)
        # Update the image URI
        NEW_TASK_DEFINITION=$(echo $TASK_DEFINITION | jq --arg IMAGE "${{ steps.build-backend-image.outputs.image }}" '.containerDefinitions[0].image = $IMAGE')
        # Remove fields that shouldn't be in the new task definition
        NEW_TASK_DEFINITION=$(echo $NEW_TASK_DEFINITION | jq 'del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .placementConstraints, .compatibilities, .registeredAt, .registeredBy)')
        # Save the new task definition
        echo "$NEW_TASK_DEFINITION" > new-task-definition-backend.json
        echo "task-definition=new-task-definition-backend.json" >> $GITHUB_OUTPUT

    - name: Fill in the new image ID in the Amazon ECS task definition (frontend)
      id: task-def-frontend
      run: |
        # Get the working task definition (revision 6) that has proper configuration
        TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition sentiment-analysis-frontend-task:6 --query taskDefinition)
        # Update the image URI
        NEW_TASK_DEFINITION=$(echo $TASK_DEFINITION | jq --arg IMAGE "${{ steps.build-frontend-image.outputs.image }}" '.containerDefinitions[0].image = $IMAGE')
        # Remove fields that shouldn't be in the new task definition
        NEW_TASK_DEFINITION=$(echo $NEW_TASK_DEFINITION | jq 'del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .placementConstraints, .compatibilities, .registeredAt, .registeredBy)')
        # Save the new task definition
        echo "$NEW_TASK_DEFINITION" > new-task-definition-frontend.json
        echo "task-definition=new-task-definition-frontend.json" >> $GITHUB_OUTPUT

    - name: Deploy Amazon ECS task definition (backend)
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def-backend.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE_BACKEND }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true

    - name: Deploy Amazon ECS task definition (frontend)
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def-frontend.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE_FRONTEND }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true
