name: Deploy SellerIQ - Smart Product Analytics

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install basic dependencies
      run: |
        python -m pip install --upgrade pip
        pip install streamlit pandas numpy requests boto3
        # Install only essential packages for basic testing
    
    - name: Test Streamlit app structure
      run: |
        python -c "
        import streamlit as st
        import os
        print('✅ Streamlit import successful')
        
        # Check if main app file exists
        if os.path.exists('dashboard/streamlit_app.py'):
            print('✅ Main app file exists')
        else:
            print('❌ Main app file not found')
            exit(1)
        
        # Check if requirements.txt exists
        if os.path.exists('requirements.txt'):
            print('✅ Requirements file exists')
        else:
            print('❌ Requirements file not found')
            exit(1)
        
        print('✅ All basic tests passed!')
        "

  deploy-to-streamlit:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Deploy to Streamlit Cloud
      run: |
        echo "🚀 SellerIQ is ready for Streamlit Cloud deployment!"
        echo "📋 Manual deployment steps:"
        echo "1. Go to https://share.streamlit.io/"
        echo "2. Sign in with GitHub"
        echo "3. Click 'New app'"
        echo "4. Select this repository"
        echo "5. Set main file path: dashboard/streamlit_app.py"
        echo "6. Click 'Deploy!'"
        echo ""
        echo "✅ Your SellerIQ app will be available at:"
        echo "https://your-app-name.streamlit.app"